apiVersion: v1
kind: ConfigMap
metadata: 
  name: mongodb-config
immutable: false
data:
  mongo_url:  "mongo.default.svc.cluster.local"
  mongo_portnumber: "27017"
  mongo_db: "todos"
  mongo_hostname: "mongo-0.mongo.default.svc.cluster.local"
  mongo_replicaset: "rs0"
  mongodb.conf: |
    storage:
      dbPath: /data/db
    replication:
        replSetName: "rs0"