apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapptodo-deployment
  labels:
    app: webapptodo
spec:
  replicas: 3
  revisionHistoryLimit: 5 # for RollingUpdate
  minReadySeconds: 5 # for RollingUpdate
  progressDeadlineSeconds: 600 # for RollingUpdate
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webapptodo
  template:
    metadata:
      labels:
        app: webapptodo
    spec:
      containers:
      - name: webapptodo
        image: gargaekansh/todoapp:tag10
        # image: gargaekansh/todoapp:tag11 # for RollingUpdate
        imagePullPolicy: Always 
        ports:
        - containerPort: 3000
        resources:
            limits:
              cpu: 100m
              memory: 500Mi
        env:
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-password 
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo_url
        -  name: MONGO_HOSTNAME
           valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo_hostname
        -  name: MONGO_PORT
           valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo_portnumber
        -  name: MONGO_DB
           valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo_db
        -  name: MONGO_REPLICASET
           valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: mongo_replicaset
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapptodo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100